name: Prettier Format Write

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  format:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm ci

      - name: Format files with Prettier
        run: npx prettier --write .

      - name: Check files with Prettier
        run: npx prettier --check .